### PR TITLE
fix: add missing support for tree ids into various existing functions

### PR DESCRIPTION
**Pull request by Darxo**
At some point you added a system with multiple Trees per PerkGroup.
Unfortunately you never updated all the utility functions in that class when doing that swap.

This PR aims to correct all functions now in that way

### CODE REVIEW

**Comment by LordMidas** [comment]
These functions used to be like this (i.e. have the ability to pass tree id), but I intentionally moved away from it. After much deliberation I reached the conclusion that these functions should just work off of the default tree - otherwise there are weird edge case situations which I don't remember anymore. Regardless, I intend to remove the ability to have multiple Trees in a perk group as it doesn't seem that useful so this will be unnecessary.

**Comment by Darxo** [comment]
Just to make it clear:
All the functions that I touched do not work currently. 
Submods are not able to use these to apply their changes.

So you will fix that then?

**Comment by Darxo** [comment]
@LordMidas afaik these functions are still broken and can't be used by submodders.
Any update for that?

**Comment by LordMidas** [comment]
> @LordMidas afaik these functions are still broken and can't be used by submodders. Any update for that?

It's fixed on the `development` branch in commit 67ac063fc1b9d6c39630f8d1a29c95657a47481d. Eventually I'll remove the `default` option from the Tree completely so this is how these functions will remain.

**Pull request closed without merging**
